# Generated by Django 5.1 on 2025-01-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_productvariantclass_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantclass',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='main_app.sizeclass'),
        ),
    ]
