# Generated by Django 5.1 on 2024-11-18 16:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_contactclass_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontentclass',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staticcontentclass',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
