# Generated by Django 5.1 on 2025-01-01 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_productvariantclass_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantclass',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='main_app.colorclass'),
        ),
        migrations.AlterField(
            model_name='productvariantclass',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='main_app.sizeclass'),
        ),
    ]
