# Generated by Django 5.1 on 2024-11-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_staticphotoclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyclass',
            name='address',
            field=models.TextField(),
        ),
    ]
