# Generated by Django 5.1 on 2024-11-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_agencyclass_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyclass',
            name='telephone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
