# Generated by Django 5.1 on 2024-11-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_agencyclass_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyclass',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='agencyclass',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='agencyclass',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
