# Generated by Django 5.1 on 2024-11-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='city',
            new_name='cityClass',
        ),
    ]
