# Generated by Django 5.1 on 2024-11-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_agencyclass_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyclass',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
