# Generated by Django 5.1 on 2024-11-20 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_agencyclass_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyclass',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ac', to='main_app.cityclass'),
        ),
    ]
