# Generated by Django 5.1 on 2024-11-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_agencyclass_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productclass',
            old_name='title',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='size',
        ),
    ]
