# Generated by Django 5.1 on 2024-11-21 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_title_productclass_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='colorClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sizeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='brandclass',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='categoryclass',
            old_name='title',
            new_name='name',
        ),
        migrations.CreateModel(
            name='productVariantClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.colorclass')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main_app.productclass')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sizeclass')),
            ],
        ),
    ]
