# Generated by Django 5.1 on 2024-11-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_colorclass_sizeclass_rename_title_brandclass_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionclass',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
