# Generated by Django 5.1 on 2024-11-21 13:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_questionclass_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionclass',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
