# Generated by Django 5.1 on 2024-11-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_brandclass_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandclass',
            name='category',
        ),
    ]
