# Generated by Django 5.1 on 2024-11-22 16:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_categoryclass_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryclass',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
