# Generated by Django 5.1 on 2024-11-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_categoryclass_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorclass',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
