# Generated by Django 5.1 on 2024-11-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_alter_productclass_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclass',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='photo',
        ),
    ]
