# Generated by Django 5.1 on 2024-11-23 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_productvariantclass_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='productImagesClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo1', models.ImageField(upload_to='images')),
                ('photo2', models.ImageField(upload_to='images')),
                ('photo3', models.ImageField(upload_to='images')),
                ('photo4', models.ImageField(upload_to='images')),
                ('photo5', models.ImageField(upload_to='images')),
                ('photo6', models.ImageField(upload_to='images')),
                ('photo7', models.ImageField(upload_to='images')),
                ('photo8', models.ImageField(upload_to='images')),
                ('photoZ1', models.ImageField(upload_to='images')),
                ('photoZ2', models.ImageField(upload_to='images')),
                ('photoZ3', models.ImageField(upload_to='images')),
                ('photoZ4', models.ImageField(upload_to='images')),
                ('photoZ5', models.ImageField(upload_to='images')),
                ('photoZ6', models.ImageField(upload_to='images')),
                ('photoZ7', models.ImageField(upload_to='images')),
                ('photoZ8', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RenameField(
            model_name='productclass',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='productvariantclass',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.productimagesclass'),
        ),
    ]
