# Generated by Django 5.1 on 2024-11-23 16:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_productimagesclass_rename_name_productclass_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
