# Generated by Django 5.1 on 2024-11-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_alter_productclass_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
