# Generated by Django 5.1 on 2024-11-23 16:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_alter_productclass_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
