# Generated by Django 5.1 on 2024-11-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_alter_productclass_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagesclass',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimagesclass',
            name='photo6',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimagesclass',
            name='photo7',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimagesclass',
            name='photo8',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimagesclass',
            name='photoZ1',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimagesclass',
            name='photoZ2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimagesclass',
            name='photoZ3',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimagesclass',
            name='photoZ4',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimagesclass',
            name='photoZ5',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimagesclass',
            name='photoZ6',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimagesclass',
            name='photoZ7',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimagesclass',
            name='photoZ8',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
