# Generated by Django 5.1 on 2024-11-23 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_alter_productimagesclass_photo5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantclass',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.productimagesclass'),
        ),
        migrations.AlterField(
            model_name='productvariantclass',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
